services:
    - type: web
      name: next-js
      env: node
      plan: starter
      buildCommand: cd client && yarn && yarn build
      startCommand: cd client && yarn start
      envVars:
          - key: NODE_ENV
            value: production
          - key: NEXT_PUBLIC_REACT_APP_SERV_PROTOCOL
            value: https://
          - key: NEXT_PUBLIC_REACT_APP_WS_PROTOCOL
            value: wss://
          - key: NEXT_PUBLIC_REACT_APP_SERV_HOSTNAME
            value: polygon-hax.herokuapp.com
          - key: NEXT_PUBLIC_REACT_APP_JWT_KEY
            value: polyhaxjwt
