import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "@styles/Home.module.css";
import { Text } from "@chakra-ui/react";

import { withCookieAuth } from "@utils/auth";
import Layout from "@layouts/Layout";
import { NextPageWithLayout } from "@utils/types";
import CreateBounty from "@components/pages/CreateBounty";
import { useRouter } from "next/router";

const CreatePage: NextPageWithLayout = () => {
  const router = useRouter();
  const { user_id } = router?.query;

  return (
    <div className={styles.container}>
      <Head>
        <title>Boards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {user_id != null ? (
          <CreateBounty userId={user_id as string} />
        ) : (
          <Text>Unable to find user and board</Text>
        )}
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

CreatePage.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};

export default withCookieAuth(CreatePage);
