import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "@styles/Home.module.css";
import { Container, Text } from "@chakra-ui/react";

import { withCookieAuth } from "@utils/auth";
import Layout from "@layouts/Layout";
import { NextPageWithLayout } from "@utils/types";
import CreateBounty from "@components/pages/CreateBounty";
import { useRouter } from "next/router";

const CreatePage: NextPageWithLayout = () => {
  const router = useRouter();
  const { twitter_handle } = router?.query;

  return (
    <Container variant="base">
      <Head>
        <title>Boards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {twitter_handle != null ? (
          <CreateBounty twitterHandle={twitter_handle as string} />
        ) : (
          <Text>Unable to find user and board</Text>
        )}
      </main>
    </Container>
  );
};

CreatePage.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};

export default withCookieAuth(CreatePage);
